### ISSUE TITLE
pnpm compile psp34 throw issue

### ISSUE THREAD

**Issue by ganesh1233456** [desoul-labs/astar-swanky-ink-template#10]
compile contract using `pnpm compile psp34` command. Got this error. I think for openbrush `3.0.0` `+nightly` requires while build contract because when I compile /contract/psp32/ with `cargo +nightly contract build` it works.

<img width="1427" alt="Screenshot 2023-03-10 at 07 17 34" src="https://user-images.githubusercontent.com/42571338/224200382-0590e104-8e86-4049-b0c8-15836e517b5e.png">

**Comment by AustinZhu** [comment]
Thank you for noticing this. Yes, you have to set the toolchain channel to nightly before using cargo-contract.

**Comment by AustinZhu** [comment]
Fixed in [35bf42adee70ee62ff265669f9f366c5c7e9a1c5](https://github.com/desoul-labs/astar-swanky-ink-template/commit/35bf42adee70ee62ff265669f9f366c5c7e9a1c5)

**Comment by ganesh1233456** [comment]
@AustinZhu  I am running those command through root folder. Even though swanky node start background. On using command for test and deploy throws this error.

<img width="1427" alt="Screenshot 2023-03-10 at 20 31 43" src="https://user-images.githubusercontent.com/42571338/224346633-ced88353-bee4-452b-bfdb-8144c4b8a914.png">
<img width="1427" alt="Screenshot 2023-03-10 at 20 32 03" src="https://user-images.githubusercontent.com/42571338/224346668-02360963-e34e-46fe-a30b-1a1cbdbc08a3.png">
